### ISSUE TITLE
importing python-multipart breaks six

### ISSUE THREAD

**Issue by WladimirSidorenko** [andrew-d/python-multipart#7]
1. Description:
Importing `python-multipart` seemingly breaks the standard `six` compatibility fixes.

2. Example:
```python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from googleapiclient.discovery import build
>>> 
```

```python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from multipart import multipart
>>> from googleapiclient.discovery import build
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sidorenko/Work/suedkurier/env/local/lib/python2.7/site-packages/googleapiclient/discovery.py", line 33, in <module>
    from six.moves.urllib.parse import urlencode, urlparse, urljoin, \
ImportError: No module named urllib.parse
```

3. System information:
```shell
uname -srm
Linux 4.4.0-53-generic x86_64

python --version
Python 2.7.12

pip --version
pip 9.0.1

pip show python-multipart
Name: python-multipart
Version: 0.0.2
Summary: A streaming multipart parser for Python
Home-page: http://github.com/andrew-d/python-multipart
Author: Andrew Dunham
Author-email: UNKNOWN
License: Apache
Location: /home/sidorenko/Work/suedkurier/env/lib/python2.7/site-packages
Requires: 

pip show google-api-python-client
Name: google-api-python-client
Version: 1.6.0
Summary: Google API Client Library for Python
Home-page: http://github.com/google/google-api-python-client/
Author: Google Inc.
Author-email: UNKNOWN
License: Apache 2.0
Location: /home/sidorenko/Work/suedkurier/env/lib/python2.7/site-packages
Requires: six, uritemplate, oauth2client, httplib2
```

**Comment by redlolgeerf** [comment]
I have the same problem
